esphome:
  name: heizungsregler-esp32
  comment: ESP32 Heizungsregelung mit MCP3208 und 100k NTC (S1->P1, LED bei Pumpenlauf)

esp32:
  board: esp32dev

logger:

api:
  encryption:
    key: !secret api_key

ota:
  - platform: esphome
    password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap:
    ssid: "Heizungsregler Fallback"
    password: "fallback1234"

# --- SPI-Bus für MCP3208 ---
spi:
  clk_pin: GPIO18
  mosi_pin: GPIO23   # DIN am MCP (vom ESP zum ADC)
  miso_pin: GPIO19   # DOUT am MCP (vom ADC zum ESP)

# --- MCP320x ADC Hub (12-bit, Vref = 2.5 V) ---
mcp3204:
  - id: mcp3208_hub
    cs_pin: GPIO5
    reference_voltage: 2.5

# ---- Schalter an IO35 (externes Pullup vorhanden, zieht bei Aktiv nach GND) ----
binary_sensor:
  - platform: gpio
    id: schalter_io35
    name: "Schalter IO35"
    pin:
      number: GPIO35
      mode:
        input: true
        pullup: false   # externer Pullup auf der Platine
      inverted: true    # aktiv, wenn auf GND gezogen
    entity_category: diagnostic

# ---- Status-LED (gegen GND getrieben) ----
output:
  - platform: gpio
    id: led_status_out
    pin:
      number: GPIO32
      inverted: false

light:
  - platform: binary
    id: led_status
    name: "Status-LED"
    output: led_status_out

# ---- Pumpen-Relais ----
switch:
  - platform: gpio
    id: pump1
    name: "Pumpe 1"
    pin: GPIO13
    on_turn_on:
      - light.turn_on: led_status
    on_turn_off:
      - light.turn_off: led_status

  - platform: gpio
    id: pump2
    name: "Pumpe 2"
    pin: GPIO14

  - platform: gpio
    id: pump3
    name: "Pumpe 3"
    pin: GPIO16

  - platform: gpio
    id: pump4
    name: "Pumpe 4"
    pin: GPIO17

# ---- ADC-Kanäle (Rohspannung in V) ----
sensor:
  - platform: mcp3204
    mcp3204_id: mcp3208_hub
    number: 0
    id: ch0_v
    name: "ADC CH0 Spannung"
    unit_of_measurement: "V"
    accuracy_decimals: 4
    update_interval: 2s

  - platform: mcp3204
    mcp3204_id: mcp3208_hub
    number: 1
    id: ch1_v
    name: "ADC CH1 Spannung"
    unit_of_measurement: "V"
    accuracy_decimals: 4
    update_interval: 2s

  - platform: mcp3204
    mcp3204_id: mcp3208_hub
    number: 2
    id: ch2_v
    name: "ADC CH2 Spannung"
    unit_of_measurement: "V"
    accuracy_decimals: 4
    update_interval: 2s

  - platform: mcp3204
    mcp3204_id: mcp3208_hub
    number: 3
    id: ch3_v
    name: "ADC CH3 Spannung"
    unit_of_measurement: "V"
    accuracy_decimals: 4
    update_interval: 2s

  - platform: mcp3204
    mcp3204_id: mcp3208_hub
    number: 4
    id: ch4_v
    name: "ADC CH4 Spannung"
    unit_of_measurement: "V"
    accuracy_decimals: 4
    update_interval: 2s

  - platform: mcp3204
    mcp3204_id: mcp3208_hub
    number: 5
    id: ch5_v
    name: "ADC CH5 Spannung"
    unit_of_measurement: "V"
    accuracy_decimals: 4
    update_interval: 2s

  - platform: mcp3204
    mcp3204_id: mcp3208_hub
    number: 6
    id: ch6_v
    name: "ADC CH6 Spannung"
    unit_of_measurement: "V"
    accuracy_decimals: 4
    update_interval: 2s

  - platform: mcp3204
    mcp3204_id: mcp3208_hub
    number: 7
    id: ch7_v
    name: "ADC CH7 Spannung"
    unit_of_measurement: "V"
    accuracy_decimals: 4
    update_interval: 2s

  # ---- Widerstand aus der Spannung (NTC nach GND -> DOWNSTREAM) ----
  # Pull-Up: 330 Ohm, Referenzspannung: 2.5 V
  - platform: resistance
    id: r1
    sensor: ch0_v
    configuration: DOWNSTREAM
    resistor: 100000 Ohm
    reference_voltage: 2.5V
    internal: true

  - platform: resistance
    id: r2
    sensor: ch1_v
    configuration: DOWNSTREAM
    resistor: 330 Ohm
    reference_voltage: 2.5V
    internal: true

  - platform: resistance
    id: r3
    sensor: ch2_v
    configuration: DOWNSTREAM
    resistor: 330 Ohm
    reference_voltage: 2.5V
    internal: true

  - platform: resistance
    id: r4
    sensor: ch3_v
    configuration: DOWNSTREAM
    resistor: 330 Ohm
    reference_voltage: 2.5V
    internal: true

  - platform: resistance
    id: r5
    sensor: ch4_v
    configuration: DOWNSTREAM
    resistor: 330 Ohm
    reference_voltage: 2.5V
    internal: true

  - platform: resistance
    id: r6
    sensor: ch5_v
    configuration: DOWNSTREAM
    resistor: 330 Ohm
    reference_voltage: 2.5V
    internal: true

  - platform: resistance
    id: r7
    sensor: ch6_v
    configuration: DOWNSTREAM
    resistor: 330 Ohm
    reference_voltage: 2.5V
    internal: true

  - platform: resistance
    id: r8
    sensor: ch7_v
    configuration: DOWNSTREAM
    resistor: 330 Ohm
    reference_voltage: 2.5V
    internal: true

  # ---- Temperatur aus dem Widerstand (100k NTC, Beta-Verfahren) ----
  - platform: ntc
    id: t1
    name: "Temperatur Sensor 1"
    sensor: r1
    unit_of_measurement: "°C"
    accuracy_decimals: 2
    device_class: temperature
    state_class: measurement
    calibration:
      b_constant: 3950
      reference_temperature: 25°C
      reference_resistance: 100kOhm

  - platform: ntc
    id: t2
    name: "Temperatur Sensor 2"
    sensor: r2
    unit_of_measurement: "°C"
    accuracy_decimals: 2
    device_class: temperature
    state_class: measurement
    calibration:
      b_constant: 3950
      reference_temperature: 25°C
      reference_resistance: 100kOhm

  - platform: ntc
    id: t3
    name: "Temperatur Sensor 3"
    sensor: r3
    unit_of_measurement: "°C"
    accuracy_decimals: 2
    device_class: temperature
    state_class: measurement
    calibration:
      b_constant: 3950
      reference_temperature: 25°C
      reference_resistance: 100kOhm

  - platform: ntc
    id: t4
    name: "Temperatur Sensor 4"
    sensor: r4
    unit_of_measurement: "°C"
    accuracy_decimals: 2
    device_class: temperature
    state_class: measurement
    calibration:
      b_constant: 3950
      reference_temperature: 25°C
      reference_resistance: 100kOhm

  - platform: ntc
    id: t5
    name: "Temperatur Sensor 5"
    sensor: r5
    unit_of_measurement: "°C"
    accuracy_decimals: 2
    device_class: temperature
    state_class: measurement
    calibration:
      b_constant: 3950
      reference_temperature: 25°C
      reference_resistance: 100kOhm

  - platform: ntc
    id: t6
    name: "Temperatur Sensor 6"
    sensor: r6
    unit_of_measurement: "°C"
    accuracy_decimals: 2
    device_class: temperature
    state_class: measurement
    calibration:
      b_constant: 3950
      reference_temperature: 25°C
      reference_resistance: 100kOhm

  - platform: ntc
    id: t7
    name: "Temperatur Sensor 7"
    sensor: r7
    unit_of_measurement: "°C"
    accuracy_decimals: 2
    device_class: temperature
    state_class: measurement
    calibration:
      b_constant: 3950
      reference_temperature: 25°C
      reference_resistance: 100kOhm

  - platform: ntc
    id: t8
    name: "Temperatur Sensor 8"
    sensor: r8
    unit_of_measurement: "°C"
    accuracy_decimals: 2
    device_class: temperature
    state_class: measurement
    calibration:
      b_constant: 3950
      reference_temperature: 25°C
      reference_resistance: 100kOhm

# ---- Bang-Bang-Regelung: Sensor 1 steuert Pumpe 1 ----
climate:
  - platform: bang_bang
    name: "S1 → Pumpe 1"
    sensor: t1
    default_target_temperature_low: 20 °C
    default_target_temperature_high: 25 °C
    cool_action:
      - switch.turn_on: pump1
    idle_action:
      - switch.turn_off: pump1

# Optional: Webserver zum Debuggen
web_server:
  port: 80
